#=========================
# Uses the following file as a template 
# when handling paired-end data
# Replace <input> with parameters
# Default values can be modified as you wish
# ========================

# === General Inputs ===
projectPrefix: <input>
outDir: <input>
pathToData: <input>
verbose: TRUE
multithread: TRUE
pathToSampleIDs: <input>
fastaPattern: [*1.fastq, *2.fastq]

# === Plot Quality ===
aggregateQual: TRUE
qualN: 5e+05

# === Downloading sequence data ===
useFastqDump: FALSE
pathToFastqDump: <input>
pathToSampleURLs: <input>

# === Dereplicate reads to keep only unique sequences ===
derepN: 1e+06

# === Detect and learn error patterns in sequences ===
errN: 1e+08
errMultithread: FALSE
saveErrorsPlot: FALSE

# === Denoise data ===
dadaBandSize: 16
dadaOmegaA: 1e-40

# === Find chimeric sequences ===
createChimeraDetectionTable: FALSE
chimeraDetectionMinSampleFraction: 0.9
chimeraDetectionIgnoreNegatives: 1
chimeraDetectionMinFoldParentOverabundance: 1.5
chimeraDetectionParentAbundance: 2
chimeraDetectionAllowOneOff: FALSE
chimeraDetectionMaxShift: 16

# === Filtering (Paired-end data example)
filtMaxEE: [2, 2]
filtTruncQ: [2, 2]
filtTruncLen: [240, 160]
filtTrimLeft: [0, 0]
filtTrimRight: [0, 0]
filtMatchIDs: FALSE
filtMinLen: [50, 50]

# === Merge Paired-end Reads ===
mergePairs: FALSE
mergePairsTrimOverhang: TRUE
mergePairsMinOverlap: 12
mergePairsMaxMismatch: 0
mergePairsReturnRejects: FALSE
mergePairsJustConcatenate: FALSE

# === Assign Taxonomy ===
taxDatabase: <input>
assignTaxMinBootstrap: 50
assignTaxTryComplement: FALSE
assignTaxOutputBootstraps: FALSE
assignTaxLevels: ["Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"]
