#=========================
# Use the following file as a template when handling single-end data
# Replace <input> with paths and/or custom parameters
# Modify default inputs as you need
# ========================

# === General Inputs ===
projectPrefix: <input>
outDir: <input>
pathToData: <input>
verbose: TRUE
multithread: TRUE
pathToSampleIDs: <input>
fastaPattern: "*.fastq(.gz)?$"

# === Plot Quality ===
aggregateQual: TRUE
qualN: 5e+05

# === Downloading sequence data ===
useFastqDump: FALSE
pathToFastqDump: path/to/fastq-dump
pathToSampleURLs: <input>

# === Dereplicate reads to keep only unique sequences ===
derepN: 1e+06

# === Detect and learn error patterns in sequences ===
errN: 1e+08
errMultithread: FALSE
saveErrorsPlot: FALSE

# === Denoise data ===
dadaBandSize: 16
dadaOmegaA: 1e-40

# === Find chimeric sequences ===
createChimeraDetectionTable: FALSE
chimeraDetectionMinSampleFraction: 0.9
chimeraDetectionIgnoreNegatives: 1
chimeraDetectionMinFoldParentOverabundance: 1.5
chimeraDetectionParentAbundance: 2
chimeraDetectionAllowOneOff: FALSE
chimeraDetectionMaxShift: 16

# === Filtering 
filtMaxEE: 2.5
filtTruncQ: 0
filtTruncLen: 0
filtTrimLeft: 0
filtTrimRight: 0
filtMatchIDs: FALSE
filtMinLen: 50

# === Merge Paired-end Reads ===
mergePairs: FALSE
mergePairsTrimOverhang: TRUE
mergePairsMinOverlap: 12
mergePairsMaxMismatch: 0
mergePairsReturnRejects: TRUE
mergePairsJustConcatenate: TRUE

# === Assign Taxonomy ===
taxDatabase: <input>
assignTaxMinBootstrap: 70
assignTaxTryComplement: FALSE
assignTaxOutputBootstraps: FALSE
assignTaxLevels: ["Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"]
